apiVersion: v1
kind: Service
metadata:
  name: artifactory-postgres-service
spec:
  selector:
    app: artifactory-postgres-database
  type: NodePort
  ports:
    - port: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: artifactory-postgres-deployment
spec:
  template:
    metadata:
      labels:
        app: artifactory-postgres-database
    spec:
      containers:
        - name: artifactory-postgres-container
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: artifactory-postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: artifactoryPostgresPassword
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: artifactoryPostgresUser
            - name: POSTGRES_DB
              value: artifactory
      volumes:
        - name: artifactory-postgres-persistent-storage
          persistentVolumeClaim:
            claimName: artifactory-postgres-pv-claim
